### ISSUE TITLE
运行崩溃

### ISSUE THREAD

**Issue by CheckTiger** [GeekGhost/Ghost#24]
com.zcy.ghost.vivideo E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.zcy.ghost.vivideo, PID: 2563
java.lang.VerifyError: io/realm/Realm
at com.zcy.ghost.vivideo.app.App.initRealm(App.java:85)
at com.zcy.ghost.vivideo.app.App.onCreate(App.java:54)

**Comment by XIyinglose** [comment]
在夜神4.4里运行失败,
 Process: com.zcy.ghost.vivideo, PID: 2337
    java.lang.NoClassDefFoundError: io.realm.internal.async.RealmThreadPoolExecutor
        at io.realm.BaseRealm.<clinit>(BaseRealm.java:72)
        at com.zcy.ghost.vivideo.app.App.initRealm(App.java:85)
        at com.zcy.ghost.vivideo.app.App.onCreate(App.java:54)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4346)
        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5019)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by caopeng000** [comment]
已修复
