### ISSUE TITLE
老哥，刚下载下来，只是RUN了一下，就报错了..

### ISSUE THREAD

**Issue by yaochangliang159** [GeekGhost/Ghost#27]
错误日志如下：
11-05 09:34:47.429 21149-21149/com.zcy.ghost.vivideo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zcy.ghost.vivideo, PID: 21149
    java.lang.VerifyError: io/realm/Realm
        at com.zcy.ghost.vivideo.app.App.initRealm(App.java:85)
        at com.zcy.ghost.vivideo.app.App.onCreate(App.java:54)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java)
        at android.app.ActivityThread.access$1600(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
        at android.os.Handler.dispatchMessage(Handler.java)
        at android.os.Looper.loop(Looper.java)
        at android.app.ActivityThread.main(ActivityThread.java)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by caopeng000** [comment]
已修复
